//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CubedCoDe.WindowsService.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CubedCoDe.WindowsService.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building repositories....
        /// </summary>
        internal static string BuildingRepositoriesLogMessage {
            get {
                return ResourceManager.GetString("BuildingRepositoriesLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking repositories for updates....
        /// </summary>
        internal static string CheckingRepositoriesForUpdatesLogMessage {
            get {
                return ResourceManager.GetString("CheckingRepositoriesForUpdatesLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploying repositories....
        /// </summary>
        internal static string DeployingRepositoriesLogMessage {
            get {
                return ResourceManager.GetString("DeployingRepositoriesLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next update will be in {0:N4} seconds..
        /// </summary>
        internal static string NextUpdateIntervalLogMessage {
            get {
                return ResourceManager.GetString("NextUpdateIntervalLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next update time is: {0}.
        /// </summary>
        internal static string NextUpdateTimeLogMessage {
            get {
                return ResourceManager.GetString("NextUpdateTimeLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem building repositories..
        /// </summary>
        internal static string ProblemBuildingRepositoriesLogMessage {
            get {
                return ResourceManager.GetString("ProblemBuildingRepositoriesLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem deploying repositories..
        /// </summary>
        internal static string ProblemDeployingRepositoriesLogMessage {
            get {
                return ResourceManager.GetString("ProblemDeployingRepositoriesLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem initialising the application due to an error in the application&apos;s configuration file..
        /// </summary>
        internal static string ProblemInitialisingApplicationLogMessage {
            get {
                return ResourceManager.GetString("ProblemInitialisingApplicationLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repositories built successfully..
        /// </summary>
        internal static string RepositoriesBuiltSuccessfullyLogMessage {
            get {
                return ResourceManager.GetString("RepositoriesBuiltSuccessfullyLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repositories deployed successfully..
        /// </summary>
        internal static string RepositoriesDeployedSuccessfullyLogMessage {
            get {
                return ResourceManager.GetString("RepositoriesDeployedSuccessfullyLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update finished..
        /// </summary>
        internal static string UpdateFinishedLogMessage {
            get {
                return ResourceManager.GetString("UpdateFinishedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating repositories....
        /// </summary>
        internal static string UpdatingRepositoriesLogMessage {
            get {
                return ResourceManager.GetString("UpdatingRepositoriesLogMessage", resourceCulture);
            }
        }
    }
}
